import {
  SCHEMA_REGISTRY_API_VERSION,
  type SchemaRegistry,
  type SearchConfig,
  type SearchFieldConfig,
} from "../../schema/registry";

const NULLABLE_STRING = { type: ["string", "null"] } as const;
const NULLABLE_NUMBER = { type: ["number", "null"] } as const;
const ATTRIBUTES_SCHEMA = { type: "object", additionalProperties: true } as const;

export const OTEL_TRACES_CANONICAL_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    schemaVersion: { type: "integer", enum: [1] },
    signal: { type: "string", enum: ["trace.span"] },
    timestamp: { type: "string" },
    endTimestamp: NULLABLE_STRING,
    startUnixNano: NULLABLE_STRING,
    endUnixNano: NULLABLE_STRING,
    duration: NULLABLE_NUMBER,
    traceId: { type: "string" },
    spanId: { type: "string" },
    parentSpanId: NULLABLE_STRING,
    traceState: NULLABLE_STRING,
    traceFlags: {
      type: "object",
      additionalProperties: false,
      properties: {
        sampled: { type: "boolean" },
        raw: { type: ["integer", "null"] },
      },
      required: ["sampled", "raw"],
    },
    name: { type: "string" },
    kind: { type: "string", enum: ["unspecified", "internal", "server", "client", "producer", "consumer"] },
    status: {
      type: "object",
      additionalProperties: false,
      properties: {
        code: { type: "string", enum: ["unset", "ok", "error"] },
        message: NULLABLE_STRING,
      },
      required: ["code", "message"],
    },
    service: NULLABLE_STRING,
    serviceNamespace: NULLABLE_STRING,
    serviceInstanceId: NULLABLE_STRING,
    environment: NULLABLE_STRING,
    version: NULLABLE_STRING,
    region: NULLABLE_STRING,
    requestId: NULLABLE_STRING,
    http: {
      type: "object",
      additionalProperties: false,
      properties: {
        method: NULLABLE_STRING,
        route: NULLABLE_STRING,
        path: NULLABLE_STRING,
        target: NULLABLE_STRING,
        url: NULLABLE_STRING,
        statusCode: { type: ["integer", "null"] },
        userAgent: NULLABLE_STRING,
      },
      required: ["method", "route", "path", "target", "url", "statusCode", "userAgent"],
    },
    db: {
      type: "object",
      additionalProperties: false,
      properties: {
        system: NULLABLE_STRING,
        name: NULLABLE_STRING,
        operation: NULLABLE_STRING,
        statement: NULLABLE_STRING,
      },
      required: ["system", "name", "operation", "statement"],
    },
    rpc: {
      type: "object",
      additionalProperties: false,
      properties: {
        system: NULLABLE_STRING,
        service: NULLABLE_STRING,
        method: NULLABLE_STRING,
      },
      required: ["system", "service", "method"],
    },
    messaging: {
      type: "object",
      additionalProperties: false,
      properties: {
        system: NULLABLE_STRING,
        destination: NULLABLE_STRING,
        operation: NULLABLE_STRING,
      },
      required: ["system", "destination", "operation"],
    },
    error: {
      type: "object",
      additionalProperties: false,
      properties: {
        isError: { type: "boolean" },
        type: NULLABLE_STRING,
        message: NULLABLE_STRING,
        stacktrace: NULLABLE_STRING,
      },
      required: ["isError", "type", "message", "stacktrace"],
    },
    instrumentationScope: {
      type: "object",
      additionalProperties: false,
      properties: {
        name: NULLABLE_STRING,
        version: NULLABLE_STRING,
        schemaUrl: NULLABLE_STRING,
        attributes: ATTRIBUTES_SCHEMA,
      },
      required: ["name", "version", "schemaUrl", "attributes"],
    },
    resource: {
      type: "object",
      additionalProperties: false,
      properties: {
        schemaUrl: NULLABLE_STRING,
        attributes: ATTRIBUTES_SCHEMA,
      },
      required: ["schemaUrl", "attributes"],
    },
    attributes: ATTRIBUTES_SCHEMA,
    events: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          timestamp: NULLABLE_STRING,
          timeUnixNano: NULLABLE_STRING,
          name: { type: "string" },
          attributes: ATTRIBUTES_SCHEMA,
          droppedAttributesCount: { type: "integer" },
        },
        required: ["timestamp", "timeUnixNano", "name", "attributes"],
      },
    },
    eventNames: {
      type: "array",
      items: { type: "string" },
    },
    links: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          traceId: { type: "string" },
          spanId: { type: "string" },
          traceState: NULLABLE_STRING,
          attributes: ATTRIBUTES_SCHEMA,
          droppedAttributesCount: { type: "integer" },
        },
        required: ["traceId", "spanId", "traceState", "attributes"],
      },
    },
    dropped: {
      type: "object",
      additionalProperties: false,
      properties: {
        attributes: { type: "integer" },
        events: { type: "integer" },
        links: { type: "integer" },
      },
      required: ["attributes", "events", "links"],
    },
    redaction: {
      type: "object",
      additionalProperties: false,
      properties: {
        keys: {
          type: "array",
          items: { type: "string" },
        },
      },
      required: ["keys"],
    },
    identity: {
      type: "object",
      additionalProperties: false,
      properties: {
        spanKey: { type: "string" },
        dedupeKey: { type: "string" },
      },
      required: ["spanKey", "dedupeKey"],
    },
  },
  required: [
    "schemaVersion",
    "signal",
    "timestamp",
    "endTimestamp",
    "startUnixNano",
    "endUnixNano",
    "duration",
    "traceId",
    "spanId",
    "parentSpanId",
    "traceState",
    "traceFlags",
    "name",
    "kind",
    "status",
    "service",
    "serviceNamespace",
    "serviceInstanceId",
    "environment",
    "version",
    "region",
    "requestId",
    "http",
    "db",
    "rpc",
    "messaging",
    "error",
    "instrumentationScope",
    "resource",
    "attributes",
    "events",
    "eventNames",
    "links",
    "dropped",
    "redaction",
    "identity",
  ],
} as const;

const exactKeyword = (jsonPointer: string, aggregatable = false): SearchFieldConfig => {
  const field: SearchFieldConfig = {
    kind: "keyword",
    bindings: [{ version: 1, jsonPointer }],
    exact: true,
    prefix: true,
    exists: true,
    sortable: true,
  };
  if (aggregatable) field.aggregatable = true;
  return field;
};

const lowercaseKeyword = (jsonPointer: string, aggregatable = false): SearchFieldConfig => ({
  ...exactKeyword(jsonPointer, aggregatable),
  normalizer: "lowercase_v1",
});

const textField = (jsonPointer: string): SearchFieldConfig => ({
  kind: "text",
  bindings: [{ version: 1, jsonPointer }],
  analyzer: "unicode_word_v1",
  exists: true,
  positions: true,
});

export const OTEL_TRACES_DEFAULT_SEARCH_CONFIG: SearchConfig = {
  profile: "otel-traces",
  primaryTimestampField: "timestamp",
  aliases: {
    db: "db.system",
    duration_ms: "duration",
    error: "error.isError",
    method: "http.method",
    op: "name",
    parent: "parentSpanId",
    req: "requestId",
    route: "http.route",
    span: "spanId",
    status: "http.statusCode",
    svc: "service",
    time: "timestamp",
    trace: "traceId",
    ts: "timestamp",
  },
  defaultFields: [
    { field: "name", boost: 2 },
    { field: "error.message", boost: 2 },
    { field: "status.message", boost: 1.5 },
    { field: "events.name", boost: 1.2 },
    { field: "db.statement", boost: 0.5 },
  ],
  fields: {
    timestamp: {
      kind: "date",
      bindings: [{ version: 1, jsonPointer: "/timestamp" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    endTimestamp: {
      kind: "date",
      bindings: [{ version: 1, jsonPointer: "/endTimestamp" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    duration: {
      kind: "float",
      bindings: [{ version: 1, jsonPointer: "/duration" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    traceId: exactKeyword("/traceId"),
    spanId: exactKeyword("/spanId"),
    parentSpanId: exactKeyword("/parentSpanId"),
    requestId: exactKeyword("/requestId"),
    service: lowercaseKeyword("/service", true),
    serviceNamespace: lowercaseKeyword("/serviceNamespace", true),
    serviceInstanceId: exactKeyword("/serviceInstanceId"),
    environment: lowercaseKeyword("/environment", true),
    version: exactKeyword("/version"),
    region: lowercaseKeyword("/region", true),
    name: {
      kind: "keyword",
      bindings: [{ version: 1, jsonPointer: "/name" }],
      exact: true,
      prefix: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    kind: lowercaseKeyword("/kind", true),
    "status.code": lowercaseKeyword("/status/code", true),
    "status.message": textField("/status/message"),
    "error.isError": {
      kind: "bool",
      bindings: [{ version: 1, jsonPointer: "/error/isError" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    "error.type": exactKeyword("/error/type", true),
    "error.message": textField("/error/message"),
    "error.stacktrace": textField("/error/stacktrace"),
    "http.method": lowercaseKeyword("/http/method", true),
    "http.route": exactKeyword("/http/route", true),
    "http.path": exactKeyword("/http/path"),
    "http.statusCode": {
      kind: "integer",
      bindings: [{ version: 1, jsonPointer: "/http/statusCode" }],
      exact: true,
      column: true,
      exists: true,
      sortable: true,
      aggregatable: true,
    },
    "db.system": lowercaseKeyword("/db/system", true),
    "db.operation": lowercaseKeyword("/db/operation", true),
    "db.statement": textField("/db/statement"),
    "rpc.system": lowercaseKeyword("/rpc/system", true),
    "rpc.service": exactKeyword("/rpc/service", true),
    "rpc.method": exactKeyword("/rpc/method", true),
    "messaging.system": lowercaseKeyword("/messaging/system", true),
    "messaging.destination": exactKeyword("/messaging/destination", true),
    "messaging.operation": lowercaseKeyword("/messaging/operation", true),
    "events.name": textField("/eventNames"),
  },
  rollups: {
    spans: {
      dimensions: ["service", "kind", "status.code"],
      intervals: ["1m", "5m", "1h"],
      measures: {
        spans: { kind: "count" },
        errors: { kind: "count", include: "error:true" },
        latency: { kind: "summary", field: "duration", histogram: "log2_v1" },
      },
    },
    http_server: {
      include: "kind:server",
      dimensions: ["service", "http.method", "http.route", "http.statusCode"],
      intervals: ["1m", "5m", "1h"],
      measures: {
        requests: { kind: "count" },
        errors: { kind: "count", include: "error:true" },
        latency: { kind: "summary", field: "duration", histogram: "log2_v1" },
      },
    },
  },
};

export function buildOtelTracesDefaultRegistry(stream: string): SchemaRegistry {
  return {
    apiVersion: SCHEMA_REGISTRY_API_VERSION,
    schema: stream,
    currentVersion: 1,
    search: structuredClone(OTEL_TRACES_DEFAULT_SEARCH_CONFIG),
    boundaries: [{ offset: 0, version: 1 }],
    schemas: {
      "1": structuredClone(OTEL_TRACES_CANONICAL_SCHEMA),
    },
    lenses: {},
  };
}
